apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-neo4j-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-neo4j-connector
  template:
    metadata:
      labels:
        app: kafka-neo4j-connector
    spec:
      containers:
      - name: kafka-neo4j-connector
        image: change1472/cse511-kafka-neo4j-connector:latest
        command: ["/bin/sh", "-c", "sh ./init.sh"]
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:29092"
        - name: TOPIC_NAME
          value: "nyc_taxicab_data"
        - name: NEO4J_URI
          value: "bolt://neo4j-service:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "processingpipeline"

